# Generated by Django 5.1 on 2024-09-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('gender', '0001_initial'), ('gender', '0002_gender_disable')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('disable', models.BooleanField(default=False)),
            ],
        ),
    ]
