# Generated by Django 5.0.7 on 2024-07-27 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("form", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(max_length=120, verbose_name="Form Name"),
                ),
                (
                    "question",
                    models.BooleanField(default=False, verbose_name="Store Responses"),
                ),
                (
                    "FormID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="form.form",
                    ),
                ),
            ],
        ),
    ]
