# Generated by Django 5.0.7 on 2024-07-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question",
            field=models.CharField(max_length=255, verbose_name="Question"),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(max_length=120, verbose_name="Question Type"),
        ),
    ]
