# Generated by Django 5.0.7 on 2024-07-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0002_alter_question_question_alter_question_question_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="question_type",
        ),
    ]
