# Generated by Django 5.0.7 on 2024-08-29 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("optionSet", "0002_remove_optionset_questionid"),
        ("question", "0003_remove_question_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="OptionSet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="optionSet.optionset",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Order"),
        ),
    ]
