# Generated by Django 5.0.7 on 2024-08-29 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0004_question_optionset_question_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="FormID",
            new_name="formID",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="OptionSet",
            new_name="optionSet",
        ),
    ]
