# Generated by Django 5.1 on 2024-09-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_rename_formid_question_formid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AddField(
            model_name='question',
            name='questionID',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
