# Generated by Django 5.1 on 2024-10-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_remove_question_id_question_questionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reverse_score',
            field=models.BooleanField(default=False, verbose_name='ReverseScore'),
        ),
    ]
