# Generated by Django 5.0.7 on 2024-10-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAvatar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravatar',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='Is Selected?'),
        ),
    ]
