# Generated by Django 5.1 on 2024-09-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('session', '0001_initial'), ('session', '0002_alter_session_end_datetime')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('pss_before', models.FloatField(blank=True, null=True)),
                ('pss_after', models.FloatField(blank=True, null=True)),
                ('sms_before', models.FloatField(blank=True, null=True)),
                ('sms_after', models.FloatField(blank=True, null=True)),
                ('physical_tiredness_before', models.FloatField(blank=True, null=True)),
                ('physical_tiredness_after', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
