# Generated by Django 5.0.7 on 2024-07-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("pss_before", models.FloatField(blank=True, null=True)),
                ("pss_after", models.FloatField(blank=True, null=True)),
                ("sms_before", models.FloatField(blank=True, null=True)),
                ("sms_after", models.FloatField(blank=True, null=True)),
                ("physical_tiredness_before", models.FloatField(blank=True, null=True)),
                ("physical_tiredness_after", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
