# Generated by Django 5.0.7 on 2024-07-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('audio_url', models.URLField()),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
