# Generated by Django 5.0.7 on 2024-08-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(default='testExercise', max_length=250),
        ),
    ]
