# Generated by Django 5.0.7 on 2024-09-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_exercise_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(default='null'),
        ),
    ]
