# Generated by Django 5.1 on 2024-09-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_exercise_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='audio_url',
            field=models.CharField(max_length=250),
        ),
    ]
