# Generated by Django 5.1 on 2024-09-23 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_alter_exercise_audio_url'),
        ('exercise', '0003_alter_exercise_description'),
    ]

    operations = [
    ]
