# Generated by Django 5.0.7 on 2024-10-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_alter_exercise_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='audio_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
