# Generated by Django 5.1 on 2024-09-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('form', '0001_initial'), ('form', '0002_form_is_compulsory_form_is_postsession_and_more')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=120, verbose_name='Form Name')),
                ('store_responses', models.BooleanField(default=False, verbose_name='Store Responses')),
                ('is_compulsory', models.BooleanField(default=False, verbose_name='Is Compulsory?')),
                ('is_postsession', models.BooleanField(default=False, verbose_name='Is Post-Session?')),
                ('is_presession', models.BooleanField(default=False, verbose_name='Is Pre-Session?')),
            ],
        ),
    ]
