# Generated by Django 5.0.7 on 2024-07-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_name",
                    models.CharField(max_length=120, verbose_name="Form Name"),
                ),
                (
                    "store_responses",
                    models.BooleanField(default=False, verbose_name="Store Responses"),
                ),
            ],
        ),
    ]
