# Generated by Django 5.1 on 2024-10-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial_squashed_0002_form_is_compulsory_form_is_postsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
