# Generated by Django 5.0.7 on 2024-08-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("optionSet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="optionset",
            name="QuestionID",
        ),
    ]
