# Generated by Django 5.0.7 on 2024-07-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('landmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('x_coordinates', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('y_coordinates', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
            ],
        ),
    ]
