# Generated by Django 5.1 on 2024-09-23 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('landmark', '0001_initial'), ('landmark', '0002_landmark_exercise_id'), ('landmark', '0003_rename_exercise_id_landmark_exercise'), ('landmark', '0004_alter_landmark_exercise'), ('landmark', '0005_landmark_landmark_image_url_landmark_landmark_name'), ('landmark', '0006_landmark_landmark_description_and_more'), ('landmark', '0006_alter_landmark_exercise_and_more'), ('landmark', '0007_merge_20240912_0543')]

    dependencies = [
        ('exercise', '0001_initial'),
        ('exercise', '0003_alter_exercise_audio_url'),
        ('exercise', '0003_alter_exercise_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('landmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('x_coordinates', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('y_coordinates', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('exercise', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landmarks', to='exercise.exercise')),
                ('landmark_image_url', models.TextField(default='null')),
                ('landmark_name', models.CharField(default='Unnamed Landmark', max_length=255)),
                ('landmark_description', models.TextField(default='null')),
            ],
        ),
    ]
