# Generated by Django 5.0.7 on 2024-07-31 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
        ('landmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='exercise_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
    ]
