# Generated by Django 5.0.7 on 2024-07-31 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0002_landmark_exercise_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landmark',
            old_name='exercise_id',
            new_name='exercise',
        ),
    ]
