# Generated by Django 5.0.7 on 2024-08-08 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
        ('landmark', '0003_rename_exercise_id_landmark_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='exercise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
    ]
