# Generated by Django 5.1 on 2024-08-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0004_alter_landmark_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='landmark_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='landmark',
            name='landmark_name',
            field=models.CharField(default='Unnamed Landmark', max_length=255),
        ),
    ]
