# Generated by Django 5.1 on 2024-08-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0005_landmark_landmark_image_url_landmark_landmark_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landmark',
            old_name='landmark_image_url',
            new_name='image_file',
        ),
    ]
