# Generated by Django 5.0.7 on 2024-09-10 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_alter_exercise_description'),
        ('landmark', '0005_landmark_landmark_image_url_landmark_landmark_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='landmark_description',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='exercise',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landmarks', to='exercise.exercise'),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='landmark_image_url',
            field=models.TextField(default='null'),
        ),
    ]
