# Generated by Django 5.0.7 on 2024-08-28 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
        ('landmark', '0005_landmark_landmark_image_url_landmark_landmark_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='exercise',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='exercise.exercise'),
        ),
    ]
