# Generated by Django 5.1 on 2024-08-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0006_rename_landmark_image_url_landmark_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='image_file',
            field=models.TextField(default='null'),
        ),
    ]
