# Generated by Django 5.0.7 on 2024-08-29 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_exercise_exercise_name'),
        ('landmark', '0006_alter_landmark_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='exercise',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landmarks', to='exercise.exercise'),
        ),
    ]
