# Generated by Django 5.1 on 2024-09-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0006_alter_landmark_exercise_and_more'),
        ('landmark', '0006_landmark_landmark_description_and_more'),
    ]

    operations = [
    ]
