# Generated by Django 5.1 on 2024-09-06 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0007_alter_landmark_exercise'),
        ('landmark', '0007_alter_landmark_image_file'),
    ]

    operations = [
    ]
