# Generated by Django 5.1 on 2024-09-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0001_initial_squashed_0007_merge_20240912_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='user_count',
            field=models.IntegerField(default=0),
        ),
    ]
