# Generated by Django 5.1 on 2024-10-05 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0008_landmark_user_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark',
            name='user_count',
        ),
    ]
