# Generated by Django 5.1 on 2024-09-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0008_merge_20240901_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landmark',
            old_name='image_file',
            new_name='landmark_image_url',
        ),
    ]
