# Generated by Django 5.0.7 on 2024-08-22 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("response", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Response",
        ),
    ]
