# Generated by Django 5.1 on 2024-09-23 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('emotion', '0001_initial'), ('emotion', '0002_emotion_colorid'), ('emotion', '0003_rename_parentid_emotion_parentid'), ('emotion', '0004_alter_emotion_value')]

    dependencies = [
        ('color', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('value', models.IntegerField(null=True)),
                ('parentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emotion.emotion')),
                ('colorID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='color.color')),
            ],
        ),
    ]
