# Generated by Django 5.0.7 on 2024-09-11 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("color", "0001_initial"),
        ("emotion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emotion",
            name="colorID",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="color.color"
            ),
            preserve_default=False,
        ),
    ]
