# Generated by Django 5.0.7 on 2024-09-11 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emotion", "0002_emotion_colorid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emotion",
            old_name="ParentID",
            new_name="parentID",
        ),
    ]
