# Generated by Django 5.0.7 on 2024-09-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emotion", "0003_rename_parentid_emotion_parentid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emotion",
            name="value",
            field=models.IntegerField(null=True),
        ),
    ]
