# Generated by Django 5.1 on 2024-09-23 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0001_initial_squashed_0001_initial'),
        ('emotion', '0001_initial_squashed_0004_alter_emotion_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='colorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='color.color'),
        ),
    ]
