# Generated by Django 5.1 on 2024-09-30 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0001_initial_squashed_0002_form_is_compulsory_form_is_postsession_and_more'),
        ('session', '0001_initial_squashed_0002_alter_session_end_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregatedScore', models.CharField(max_length=125, verbose_name='Response')),
                ('FormID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.form')),
                ('SessionID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='session.session')),
            ],
        ),
    ]
