# Generated by Django 5.0.7 on 2024-07-27 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("form", "0001_initial"),
        ("session", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FormID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="form.form",
                    ),
                ),
                (
                    "SessionId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="session.session",
                    ),
                ),
            ],
            options={
                "ordering": ["SessionId", "FormID"],
                "unique_together": {("SessionId", "FormID")},
            },
        ),
    ]
