# Generated by Django 5.0.7 on 2024-08-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formSession", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FormSession",
        ),
    ]
