# Generated by Django 5.1 on 2024-09-23 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('formQuestion', '0001_initial'), ('formQuestion', '0002_alter_formquestion_unique_together')]

    dependencies = [
        ('question', '0003_remove_question_question_type'),
        ('session', '0002_alter_session_end_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Response', models.CharField(max_length=125, verbose_name='Response')),
                ('QuestionID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('SessionID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='session.session')),
            ],
            options={
                'unique_together': set(),
            },
        ),
    ]
