# Generated by Django 5.1 on 2024-09-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formQuestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formquestion',
            unique_together=set(),
        ),
    ]
