# Generated by Django 5.1 on 2024-09-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formQuestion', '0002_alter_formquestion_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formquestion',
            name='QuestionID',
        ),
    ]
