# Generated by Django 5.1 on 2024-09-24 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formQuestion', '0003_remove_formquestion_questionid'),
        ('question', '0006_remove_question_id_question_questionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestion',
            name='QuestionID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.question'),
        ),
    ]
