# Generated by Django 5.0.7 on 2024-10-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=100)),
                ('processed_contents', models.TextField(default='null')),
                ('article_pdf_url', models.CharField(max_length=255)),
                ('article_image_url', models.CharField(max_length=255)),
            ],
        ),
    ]
