# Generated by Django 5.0.7 on 2024-11-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('achievement_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='null', max_length=255)),
                ('streak_count', models.IntegerField(default=1)),
                ('achievement_badge_url', models.TextField(default='null')),
            ],
        ),
    ]
