# Generated by Django 5.1 on 2024-09-12 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landmark', '0007_merge_20240912_0543'),
        ('session', '0002_alter_session_end_datetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersessions', to='landmark.landmark')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersessions', to='session.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'landmark', 'session'), name='unique_user_landmark_session')],
            },
        ),
    ]
