# Generated by Django 4.2.16 on 2024-11-03 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("article", "0002_article_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                ("searchID", models.AutoField(primary_key=True, serialize=False)),
                ("query", models.CharField(max_length=255, verbose_name="Query")),
                (
                    "rankPosition",
                    models.IntegerField(default=0, verbose_name="RankPosition"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "articleID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_clicks",
                        to="article.article",
                    ),
                ),
                (
                    "userID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "search_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["userID"], name="search_hist_userID__4d3eed_idx"
                    ),
                    models.Index(fields=["query"], name="search_hist_query_69a772_idx"),
                    models.Index(
                        fields=["created_at"], name="search_hist_created_7f2b0d_idx"
                    ),
                ],
            },
        ),
    ]
