# Generated by Django 5.1 on 2024-09-23 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('journal', '0001_initial'), ('journal', '0002_journal_user_id'), ('journal', '0003_rename_audio_to_text_journal_journal_text'), ('journal', '0004_alter_journal_emotion_id'), ('journal', '0005_journal_title'), ('journal', '0006_remove_journal_emotion_id'), ('journal', '0007_journal_emotion_id'), ('journal', '0008_alter_journal_emotion_id')]

    dependencies = [
        ('emotion', '0004_alter_emotion_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file_path', models.CharField(max_length=255)),
                ('journal_text', models.TextField()),
                ('sentiment_analysis_result', models.TextField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(default=1, max_length=255)),
                ('emotion_id', models.ManyToManyField(related_name='journals', to='emotion.emotion')),
            ],
        ),
    ]
