# Generated by Django 5.0.7 on 2024-07-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emotion_id", models.IntegerField()),
                ("audio_file_path", models.CharField(max_length=255)),
                ("journal_text", models.TextField()),
                ("sentiment_analysis_result", models.TextField()),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
