# Generated by Django 5.0.7 on 2024-08-12 07:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_journal_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="journal",
            old_name="journal_text",
            new_name="journal_text",
        ),
    ]
