# Generated by Django 5.0.7 on 2024-09-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0004_alter_journal_emotion_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="title",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
