# Generated by Django 5.0.7 on 2024-09-12 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0005_journal_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journal",
            name="emotion_id",
        ),
    ]
