# Generated by Django 5.0.7 on 2024-09-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emotion", "0004_alter_emotion_value"),
        ("journal", "0006_remove_journal_emotion_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="emotion_id",
            field=models.ManyToManyField(to="emotion.emotion"),
        ),
    ]
