# Generated by Django 5.0.7 on 2024-09-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emotion", "0004_alter_emotion_value"),
        ("journal", "0007_journal_emotion_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="emotion_id",
            field=models.ManyToManyField(related_name="journals", to="emotion.emotion"),
        ),
    ]
