# Generated by Django 5.0.7 on 2024-10-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('avatar_id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar_url', models.TextField(default='null')),
                ('fragments_required', models.IntegerField(default=1)),
                ('drop_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
