# Generated by Django 5.0.7 on 2024-10-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='title',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
