# Generated by Django 5.1 on 2024-09-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('color', '0001_initial')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hexcode', models.CharField(max_length=100)),
            ],
        ),
    ]
