# Generated by Django 5.1 on 2024-09-23 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('option', '0001_initial')]

    dependencies = [
        ('optionSet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('value', models.FloatField(blank=True, null=True)),
                ('OptionSetID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optionSet.optionset')),
            ],
        ),
    ]
