# Generated by Django 5.0.7 on 2024-10-07 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0001_initial_squashed_0001_initial'),
        ('optionSet', '0001_initial_squashed_0002_remove_optionset_questionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='OptionSetID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='optionSet.optionset'),
        ),
    ]
