# Generated by Django 5.1 on 2024-10-05 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landmark', '0009_remove_landmark_user_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandmarkUserCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_count', models.IntegerField(default=0)),
                ('landmark', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_count', to='landmark.landmark')),
            ],
        ),
    ]
