# Generated by Django 5.0.7 on 2024-08-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="disable",
            field=models.BooleanField(default=False),
        ),
    ]
