# Generated by Django 5.0.7 on 2024-08-11 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gender", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gender.gender"
            ),
        ),
    ]
