# Generated by Django 5.0.7 on 2024-08-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_customuser_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="login_streak",
            field=models.IntegerField(default=0),
        ),
    ]
