# Generated by Django 5.0.7 on 2024-08-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_customuser_login_streak"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(default="insert name", max_length=150),
            preserve_default=False,
        ),
    ]
